FROM golang:latest

COPY config.sh .
RUN /bin/bash -c 'source config.sh'

# CMD /bin/bash -c 'source config.sh && echo $RRRRRRRRRRRRRRRSS_FEED_USERNAME'
CMD /bin/bash -c 'echo $RRRRRRRRRRRRRRRSS_FEED_USERNAME'
